// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0SWLSdYpeGEKQfBwT-EBhVj3RHr1Or6s',
    appId: '1:587105600363:android:45b4588828d84054c8022e',
    messagingSenderId: '587105600363',
    projectId: 'saraapplication-d20e4',
    databaseURL: 'https://saraapplication-d20e4-default-rtdb.firebaseio.com',
    storageBucket: 'saraapplication-d20e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuVDM8MYfRVKrOxcXUedg2SNXi1PDpmEw',
    appId: '1:587105600363:ios:2b1b187c1efd4390c8022e',
    messagingSenderId: '587105600363',
    projectId: 'saraapplication-d20e4',
    databaseURL: 'https://saraapplication-d20e4-default-rtdb.firebaseio.com',
    storageBucket: 'saraapplication-d20e4.appspot.com',
    iosClientId: '587105600363-bllipopq7n9ihljpbo9guh0c1qcm17o4.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled16',
  );
}
